fix: seed faker so it generates deterministic data
* fix: seed faker so it generates deterministic data

This will hopefully fix our intermitent errors for unique constraint
violations like

```
QueryFailedError: duplicate key value violates unique constraint ...
```

and make it easier to repo CI test failures in general

Half prove that this fix works, if you seed the acceptance tests
with 123, they will fail every time you run them.

* fix: seed beforeeach

so that data is generated independant of previous tests run

* fix: code lost in bad rebase


Approved-by: Oliver Harrison
Approved-by: Matthew Carey